name: Print Me

on: push

jobs:
  printme:
    runs-on: ubuntu-latest
    steps:
      - name: yooo print
        env:
          ref: ${{ env.GITHUB_REF_NAME }}
          sha: ${{ github.GITHUB_SHA }}
        run: |
          echo $ref
          echo ${GITHUB_REF##*/}
          echo `$sha`
          echo "Event name: ${{ github.event_name }}"
          echo "GITHUB_HEAD_REF: ${{ github.head_ref }}"
          echo "GITHUB_HEAD_REF: ${{ github.HEAD_REF }}"
          echo "Github sha: ${{ github.sha }}"
          env
