name: Print Me

on: push

jobs:
  printme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: yooo print
        env:
          ref: ${{ env.GITHUB_REF_NAME }}
        run: |
          echo ${{ env.ref }}
          echo ${GITHUB_REF##*/}
          echo "Event name: ${{ github.event_name }}"
          echo "GITHUB_HEAD_REF: ${{ github.GITHUB_HEAD_REF }}"
          echo "Github sha: ${{ github.GITHUB_SHA }}"
