name: Print Me

on:
  push:
  pull_request:
    types: 
      - opened
      - reopened
      - closed


jobs:
  printme:
    runs-on: ubuntu-latest

    env:
      JOB_ENV: poiuytre

    steps:
      - name: yooo print
        env:
          ref: ${{ env.GITHUB_REF_NAME }}
          sha: ${{ github.GITHUB_SHA }}
        run: |
          echo '${{ env.ref }}          : ' ${{ env.ref }}""
          echo '$JOB_ENV                : ' $JOB_ENV
          echo '${GITHUB_REF##*/}       : ' ${GITHUB_REF##*/}
          echo '$sha                    : ' $sha
          echo '${{ github.event_name }}: ' "${{ github.event_name }}"
          echo '${{ github.head_ref }}  : ' "${{ github.head_ref }}"
          echo '${{ github.HEAD_REF }}  : ' "${{ github.HEAD_REF }}"
          echo '${{ github.sha }}       : ' "${{ github.sha }}"
          echo '${{ github.GITHUB_REF }}: ' "${{ github.GITHUB_REF }}"
          echo "========================================================================"
          env
