name: Print Me

on:
  push:
  pull_request:
    types: 
      - opened
      - reopened
      - closed



jobs:
  printme:
    runs-on: ubuntu-latest

    env:
      JOB_ENV: poiuytre

    steps:
      - name: yooo print
        env:
          ref: ${{ env.GITHUB_REF_NAME }}
          sha: ${{ github.GITHUB_SHA }}
        run: |
          echo '{{ env.ref }}           : ' ${{ env.ref }}""
          echo '$JOB_ENV                : ' $JOB_ENV
          echo '$\{GITHUB_REF##*/}      : ' ${GITHUB_REF##*/}
          echo '$\{GITHUB_REF}          : ' ${GITHUB_REF}
          echo '$sha                    : ' $sha
          echo '{{ github.event_name }} : ' ${{ github.event_name }}
          echo '{{ github.head_ref }}   : ' ${{ github.head_ref }}
          echo '{{ github.HEAD_REF }}   : ' ${{ github.HEAD_REF }}
          echo '{{ github.base_ref }}   : ' ${{ github.base_ref }}
          echo '{{ github.sha }}        : ' ${{ github.sha }}
          echo '{{ github.GITHUB_REF }} : ' ${{ github.GITHUB_REF }}
          echo "========================================================================"
          env
          
          
#       - uses: actions/checkout@v3
#       - uses: dev-drprasad/delete-tag-and-release@v1.0 # PRERELEASE is v1.0 and can also be used to test and give us feedback
#         with:
#           tag_name: qweqweqwe #(required) tag name to delete 
#           github_token: ${{ secrets.NEWTOKEN }} # (required) a GitHub token with write access to the repo that needs to be modified

#       - name: < Auto Tag > 
#         # good
#         uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
#         env:
#           GITHUB_TOKEN: ${{ secrets.NEWTOKEN }} # if you don't want to set write permissions use a PAT token
#           WITH_V: false
#           CUSTOM_TAG: qweqweqwe
          
#         # Good
#         id: tag_version
#         uses: mathieudutour/github-tag-action@v6.1
#         with:
#           github_token: ${{ secrets.NEWTOKEN }}
#           custom_tag: "XDDD"



        # Fail
      - uses: actions/checkout@v3
      - name: tag
        uses: rickstaa/action-create-tag@v1.6.2
        with:
          github_token: ${{ secrets.NEWTOKEN }}
          tag: QQ
          force_push_tag: true

          
          
          

#   python:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - name: Set up Python 3.11
#         uses: actions/setup-python@v4
#         with:
#           python-version: 3.11

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install PyGithub
      
#       - name: Python print
#         run: |
#           python action.py "${GITHUB_REF}" ${{ secrets.newtoken }}

#   if_merged:
#     if: github.event.pull_request.merged == true
#     runs-on: ubuntu-latest
#     steps:
#     - run: |
#         echo The PR was merged
